//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionEscritorio.ServicioFinal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Banco", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Banco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AplicacionEscritorio.ServicioFinal.Jugador))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AplicacionEscritorio.ServicioFinal.Administrador))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreLogueoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreLogueo {
            get {
                return this.NombreLogueoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreLogueoField, value) != true)) {
                    this.NombreLogueoField = value;
                    this.RaisePropertyChanged("NombreLogueo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Jugador : AplicacionEscritorio.ServicioFinal.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServicioFinal.Administrador UnAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServicioFinal.Banco UnBancoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBanco {
            get {
                return this.NombreBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBancoField, value) != true)) {
                    this.NombreBancoField = value;
                    this.RaisePropertyChanged("NombreBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuenta {
            get {
                return this.NumeroCuentaField;
            }
            set {
                if ((this.NumeroCuentaField.Equals(value) != true)) {
                    this.NumeroCuentaField = value;
                    this.RaisePropertyChanged("NumeroCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServicioFinal.Administrador UnAdmin {
            get {
                return this.UnAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.UnAdminField, value) != true)) {
                    this.UnAdminField = value;
                    this.RaisePropertyChanged("UnAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServicioFinal.Banco UnBanco {
            get {
                return this.UnBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnBancoField, value) != true)) {
                    this.UnBancoField = value;
                    this.RaisePropertyChanged("UnBanco");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrador", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Administrador : AplicacionEscritorio.ServicioFinal.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EjecutaSoteosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EjecutaSoteos {
            get {
                return this.EjecutaSoteosField;
            }
            set {
                if ((this.EjecutaSoteosField.Equals(value) != true)) {
                    this.EjecutaSoteosField = value;
                    this.RaisePropertyChanged("EjecutaSoteos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugada", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Jugada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ElJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraSorteoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServicioFinal.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] NumerosJugadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServicioFinal.Sorteo unSorteoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElJugador {
            get {
                return this.ElJugadorField;
            }
            set {
                if ((this.ElJugadorField.Equals(value) != true)) {
                    this.ElJugadorField = value;
                    this.RaisePropertyChanged("ElJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraSorteo {
            get {
                return this.FechaHoraSorteoField;
            }
            set {
                if ((this.FechaHoraSorteoField.Equals(value) != true)) {
                    this.FechaHoraSorteoField = value;
                    this.RaisePropertyChanged("FechaHoraSorteo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServicioFinal.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] NumerosJugados {
            get {
                return this.NumerosJugadosField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerosJugadosField, value) != true)) {
                    this.NumerosJugadosField = value;
                    this.RaisePropertyChanged("NumerosJugados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServicioFinal.Sorteo unSorteo {
            get {
                return this.unSorteoField;
            }
            set {
                if ((object.ReferenceEquals(this.unSorteoField, value) != true)) {
                    this.unSorteoField = value;
                    this.RaisePropertyChanged("unSorteo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sorteo", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Sorteo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] NumerosSorteadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] NumerosSorteados {
            get {
                return this.NumerosSorteadosField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerosSorteadosField, value) != true)) {
                    this.NumerosSorteadosField = value;
                    this.RaisePropertyChanged("NumerosSorteados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFinal.IServicioProyectoFinal")]
    public interface IServicioProyectoFinal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/AltaBanco", ReplyAction="http://tempuri.org/IServicioProyectoFinal/AltaBancoResponse")]
        void AltaBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BajaBanco", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BajaBancoResponse")]
        void BajaBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ModificarBanco", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ModificarBancoResponse")]
        void ModificarBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BuscarBanco", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BuscarBancoResponse")]
        AplicacionEscritorio.ServicioFinal.Banco BuscarBanco(string pRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarBancos", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarBancosResponse")]
        AplicacionEscritorio.ServicioFinal.Banco[] ListarBancos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/LogueoUsuario", ReplyAction="http://tempuri.org/IServicioProyectoFinal/LogueoUsuarioResponse")]
        AplicacionEscritorio.ServicioFinal.Usuario LogueoUsuario(string pNombreUsuario, string pContrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BuscarUsuario", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BuscarUsuarioResponse")]
        AplicacionEscritorio.ServicioFinal.Usuario BuscarUsuario(int pDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/AltaUsuario", ReplyAction="http://tempuri.org/IServicioProyectoFinal/AltaUsuarioResponse")]
        void AltaUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BajaUsuario", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BajaUsuarioResponse")]
        void BajaUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ModificarUsuarioResponse")]
        void ModificarUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/AltaUsuarioLogueoYBD", ReplyAction="http://tempuri.org/IServicioProyectoFinal/AltaUsuarioLogueoYBDResponse")]
        void AltaUsuarioLogueoYBD(AplicacionEscritorio.ServicioFinal.Usuario pUsuario, string pRol, string pPermiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarAdministradores", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarAdministradoresResponse")]
        AplicacionEscritorio.ServicioFinal.Administrador[] ListarAdministradores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarJugadasDeJugador", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarJugadasDeJugadorResponse")]
        AplicacionEscritorio.ServicioFinal.Jugada[] ListarJugadasDeJugador(AplicacionEscritorio.ServicioFinal.Jugador pJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/GenerarJugada", ReplyAction="http://tempuri.org/IServicioProyectoFinal/GenerarJugadaResponse")]
        void GenerarJugada(AplicacionEscritorio.ServicioFinal.Jugada jugada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BuscarJugada", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BuscarJugadaResponse")]
        AplicacionEscritorio.ServicioFinal.Jugada BuscarJugada(AplicacionEscritorio.ServicioFinal.Jugador jugador, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarJugadasPremiadas", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarJugadasPremiadasResponse")]
        string ListarJugadasPremiadas(AplicacionEscritorio.ServicioFinal.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarJugadasPremiadasPorSorteo", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarJugadasPremiadasPorSorteoResponse" +
            "")]
        AplicacionEscritorio.ServicioFinal.Jugada[] ListarJugadasPremiadasPorSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/GenerarSorteo", ReplyAction="http://tempuri.org/IServicioProyectoFinal/GenerarSorteoResponse")]
        void GenerarSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/RealizarSorteo", ReplyAction="http://tempuri.org/IServicioProyectoFinal/RealizarSorteoResponse")]
        void RealizarSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/BuscarSorteo", ReplyAction="http://tempuri.org/IServicioProyectoFinal/BuscarSorteoResponse")]
        AplicacionEscritorio.ServicioFinal.Sorteo BuscarSorteo(System.DateTime pFechaHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarSorteosDisponibles", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarSorteosDisponiblesResponse")]
        AplicacionEscritorio.ServicioFinal.Sorteo[] ListarSorteosDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProyectoFinal/ListarSorteosDisponiblesJugador", ReplyAction="http://tempuri.org/IServicioProyectoFinal/ListarSorteosDisponiblesJugadorResponse" +
            "")]
        AplicacionEscritorio.ServicioFinal.Sorteo[] ListarSorteosDisponiblesJugador(AplicacionEscritorio.ServicioFinal.Jugador jugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProyectoFinalChannel : AplicacionEscritorio.ServicioFinal.IServicioProyectoFinal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProyectoFinalClient : System.ServiceModel.ClientBase<AplicacionEscritorio.ServicioFinal.IServicioProyectoFinal>, AplicacionEscritorio.ServicioFinal.IServicioProyectoFinal {
        
        public ServicioProyectoFinalClient() {
        }
        
        public ServicioProyectoFinalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProyectoFinalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProyectoFinalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProyectoFinalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco) {
            base.Channel.AltaBanco(pBanco);
        }
        
        public void BajaBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco) {
            base.Channel.BajaBanco(pBanco);
        }
        
        public void ModificarBanco(AplicacionEscritorio.ServicioFinal.Banco pBanco) {
            base.Channel.ModificarBanco(pBanco);
        }
        
        public AplicacionEscritorio.ServicioFinal.Banco BuscarBanco(string pRut) {
            return base.Channel.BuscarBanco(pRut);
        }
        
        public AplicacionEscritorio.ServicioFinal.Banco[] ListarBancos() {
            return base.Channel.ListarBancos();
        }
        
        public AplicacionEscritorio.ServicioFinal.Usuario LogueoUsuario(string pNombreUsuario, string pContrasenia) {
            return base.Channel.LogueoUsuario(pNombreUsuario, pContrasenia);
        }
        
        public AplicacionEscritorio.ServicioFinal.Usuario BuscarUsuario(int pDocumento) {
            return base.Channel.BuscarUsuario(pDocumento);
        }
        
        public void AltaUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario) {
            base.Channel.AltaUsuario(pUsuario);
        }
        
        public void BajaUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario) {
            base.Channel.BajaUsuario(pUsuario);
        }
        
        public void ModificarUsuario(AplicacionEscritorio.ServicioFinal.Usuario pUsuario) {
            base.Channel.ModificarUsuario(pUsuario);
        }
        
        public void AltaUsuarioLogueoYBD(AplicacionEscritorio.ServicioFinal.Usuario pUsuario, string pRol, string pPermiso) {
            base.Channel.AltaUsuarioLogueoYBD(pUsuario, pRol, pPermiso);
        }
        
        public AplicacionEscritorio.ServicioFinal.Administrador[] ListarAdministradores() {
            return base.Channel.ListarAdministradores();
        }
        
        public AplicacionEscritorio.ServicioFinal.Jugada[] ListarJugadasDeJugador(AplicacionEscritorio.ServicioFinal.Jugador pJugador) {
            return base.Channel.ListarJugadasDeJugador(pJugador);
        }
        
        public void GenerarJugada(AplicacionEscritorio.ServicioFinal.Jugada jugada) {
            base.Channel.GenerarJugada(jugada);
        }
        
        public AplicacionEscritorio.ServicioFinal.Jugada BuscarJugada(AplicacionEscritorio.ServicioFinal.Jugador jugador, int id) {
            return base.Channel.BuscarJugada(jugador, id);
        }
        
        public string ListarJugadasPremiadas(AplicacionEscritorio.ServicioFinal.Jugador jugador) {
            return base.Channel.ListarJugadasPremiadas(jugador);
        }
        
        public AplicacionEscritorio.ServicioFinal.Jugada[] ListarJugadasPremiadasPorSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo) {
            return base.Channel.ListarJugadasPremiadasPorSorteo(sorteo);
        }
        
        public void GenerarSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo) {
            base.Channel.GenerarSorteo(sorteo);
        }
        
        public void RealizarSorteo(AplicacionEscritorio.ServicioFinal.Sorteo sorteo) {
            base.Channel.RealizarSorteo(sorteo);
        }
        
        public AplicacionEscritorio.ServicioFinal.Sorteo BuscarSorteo(System.DateTime pFechaHora) {
            return base.Channel.BuscarSorteo(pFechaHora);
        }
        
        public AplicacionEscritorio.ServicioFinal.Sorteo[] ListarSorteosDisponibles() {
            return base.Channel.ListarSorteosDisponibles();
        }
        
        public AplicacionEscritorio.ServicioFinal.Sorteo[] ListarSorteosDisponiblesJugador(AplicacionEscritorio.ServicioFinal.Jugador jugador) {
            return base.Channel.ListarSorteosDisponiblesJugador(jugador);
        }
    }
}
